### ISSUE TITLE
Joomla usuability

### ISSUE THREAD

**Issue by davidjosephhayes** [teamsinger/uk.teamsinger.civicrm.mailgun#15]
As of CiviCRM 4.5.5 you run into an issue with Joomla. On line 46 of the the public entry way (j! install)/components/com_civicrm/civicrm.php, there is a check for $_POST vars. If they are found, it checks for a initialized session. This triggers a redirect out of the application before any IDS checks, or any of the extensions is run.
```
// check and ensure that we have a valid session
  if (!empty($_POST)) {
    // the session should not be empty
    // however for standalone forms, it will not have any CiviCRM variables in the
    // session either, so dont check for it
    if (count($_SESSION) <= 1) {
      $config = CRM_Core_Config::singleton();
      CRM_Utils_System::redirect($config->userFrameworkBaseURL);
    }
```

**Comment by tomsinger** [comment]
Hrm, that's annoying. Probably the correct way around this would be to use the API to post the data to but then would this kick in before the API call as well?

I've not used Civi with Joomla, any ideas on how to better get around this?

**Comment by davidjosephhayes** [comment]
I made a pull request to change the civicrm Joomla component, but have not heard back from them yet: https://github.com/civicrm/civicrm-joomla/pull/27

I can understand the check for an initialized session, but I have no idea why you would require more than one session member.

**Comment by tomsinger** [comment]
They've merged your pull request now, is this resolved at the Joomla end? If so can I close this issue?

**Comment by davidjosephhayes** [comment]
Yep!
