### ISSUE TITLE
Where is the API key stored

### ISSUE THREAD

**Issue by alanef** [teamsinger/uk.teamsinger.civicrm.mailgun#18]
I see that you are validating the webhook  using the mailgun apikey,

but I wonder if you could give me a little guidance where you are reading the MailGun api key from

      if ($api->MailSettings->Getsingle( $params )) {
           $apiKey = $api->password;
         }

As I can't work it out (lack of familiarity with CiviCrM)

**Comment by alanef** [comment]
For the moment I have just commented out the code to check the hash until I can work this out / get an answer

**Comment by tomsinger** [comment]
This is the password for the mail account updated in step 3, I've added this into the README. I'll close this but please reopen if this doesn't work for you.

**Comment by alanef** [comment]
Thanks, I nearly got there. All tested and working.
